version: '3.4'

services:
  catalogdb:
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
    - catalogdb
    ports:
    - "3000:8080"
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=redis://basketdb:6379"
    depends_on:
    - basketdb
    ports:
    - "3001:8080"

volumes:
  mongo_data: