version: "3.4"

services:
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine 
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
      
  basket.api:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
      
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount.API/Dockerfile
      
  discountdb:
    image: postgres
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  pgadmin:
    image: dpage/pgadmin4
    
  portainer:
    image: portainer/portainer-ce
    
  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Ordering.API/Dockerfile
      
  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: Ocelot.ApiGateway/Dockerfile
    
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: