version: '3.4'

services:
  catalogdb:
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
    - catalogdb
    ports:
    - "3000:8080"

volumes:
  mongo_data: